---
- hosts: all
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root  
  tasks:
  - name: Set the tomcat port to non-default value
    xml: 
      path: /usr/share/tomcat/conf/server.xml
      xpath: /Server/Connector/@port
      value: "{{ tomcat_port }}"
    notify: restart tomcat

  - name: restart tomcat
    service:
      name: tomcat
      state: restarted