- name: Install Java App on jboss
  hosts: all
  tasks:
    - name: Download Java application
      get_url:
        url: https://tomcat.apache.org/tomcat-9.0-doc/appdev/sample/sample.war
        dest: /usr/share/jboss-as/standalone/deployments/sample.war
        mode: 0777
      notify:
      - restart jboss
  handlers:
    - name: restart jboss
      service: name=jboss state=restarted