--- # Bootstrap webservers
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd
    - name: create index.html file
      file:
        name: /var/www/html/index.html
        state: touch
    - name: add web content
      lineinfile:
        line: "<html> <h1> Hello World!! </h1></html>"
        path: /var/www/html/index.html
      notify:
        - restart httpd                 # A change in task yum will call the handler restart httpd
  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd