--- # Bootstrap webservers
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd
    - name: create index.html file
      file:
        name: /var/www/html/index.html
        state: touch
    - name: add web content
      lineinfile:
        line: "Hello World!!"
        path: /var/www/html/index.html
      notify:
        - restart httpd                 # A change in task yum will call the handler restart httpd
    - name: Unarchive a html package to web directory
      unarchive:
        src: https://github.com/diimallya/http-packages/blob/master/home_shoppe-web_Free26-10-2017_607046700.zip
        dest: /var/www/html/
        remote_src: yes
      notify:
        - restart httpd   

  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd