--- # Bootstrap webservers
- hosts: all
  become: yes
  tasks:
    - name: Installs nginx web server
      apt: name=nginx state=present update_cache=true
      notify:
        - start nginx

    - name: Upload default index.html for host
      copy: src=/var/www/html/index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
    - name: start nginx
      service: name=nginx state=present