--- # Bootstrap webservers
- hosts: all
  become: yes
  tasks:
    - name: Installs nginx web server
      yum: name=nginx state=present update_cache=true
      notify:
        - start nginx
    - name: create index.html file
      file:
        name: /usr/share/nginx/html/index.html
        state: touch
    - name: add web content
      lineinfile:
        line: "<html> <h1> Hello World!! </h1></html>"
        path: /usr/share/nginx/html/index.html
      notify:
        - start nginx      
    

  handlers:
    - name: start nginx
      service: name=nginx state=restarted


