--- # Bootstrap webservers
- hosts: all
  become: yes               # If to escalate privilege
  become_method: sudo 
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd
    - name: create index.html file
      file:
        name: /var/www/html/index.html
        state: touch
    - name: add web content
      lineinfile:
        line: "Hello World!!"
        path: /var/www/html/index.html
      notify:
        - restart httpd                 # A change in task yum will call the handler restart httpd

    - name: Download http package
      get_url:
        url: https://github.com/diimallya/http-packages/blob/master/static.zip
        dest: /tmp/staic.zip
        mode: 0777

    - name: Unarchive a html package to web directory
      unarchive:
        src: /tmp/staic.zip
        dest: /var/www/html/
        remote_src: yes
      notify:
        - restart httpd   

  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd