--- # Bootstrap webservers
- hosts: all
  become: yes               # If to escalate privilege
  become_method: sudo 
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd

    - name: dDownload http package
      get_url:
        url: https://github.com/diimallya/http-packages/blob/master/static.tgz
        dest: /tmp/static.tgz
        mode: 0777

    - name: Extract http package into webserver directory
      shell: mkdir /var/www/html
      shell: cp -r /tmp/static.tgz /var/www/html/
      notify:
        - restart httpd

  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd