--- # Bootstrap webservers
- hosts: all
  become: yes               # If to escalate privilege
  become_method: sudo 
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd

    - name: Download http package
      get_url:
        url: https://github.com/diimallya/http-packages/blob/master/static.zip
        dest: /tmp/static.zip
        mode: 0777

    - name: Unarchive a html package to web directory
      command: sudo unzip /tmp/static.zip -d /var/www/html/
      notify:
        - restart httpd

  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd