--- # Bootstrap webservers
- hosts: all
  become: yes               # If to escalate privilege
  become_method: sudo 
  gather_facts: yes
  tasks:
    - name: install latest httpd
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd

    - name: Extract http package into webserver directory
      unarchive:
        src: https://github.com/diimallya/http-packages/blob/master/new-static.tar.gz
        dest: /var/www/html/
        remote_src: yes
      notify:
        - restart httpd                  # A change in task yum will call the handler restart httpd

  handlers:
    - name: Attempt to restart httpd
      service:
        name: httpd
        state: restarted
      listen: restart httpd