---
- hosts: all
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: Stop Tomcat
      command: sh /usr/share/tomcat/bin/shutdown.sh
      become: true
      become_user: tomcat

    - name: Remove Tomcat
      file:
        path: usr/share/tomcat
        state: absent

    - name: remove user "tomcat"
      user:
        name: tomcat
        state: absent

    - name: remove group "tomcat"
      group:
        name: tomcat
        state: absent